services:
  a2-app-ci:
    image: faiqabbasi202/ignition-insights:latest
    environment:
      - MONGO_URL=mongodb://a2-mongo-ci:27017/ignition
    container_name: a2-app-ci
    ports:
      - "8081:8080"           # App runs on port 8081 externally
    depends_on:
      - a2-mongo-ci
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 5

  a2-mongo-ci:
    image: mongo:6
    container_name: a2-mongo-ci
    ports:
      - "27018:27017"         # Separate Mongo port
    volumes:
      - mongo_data_ci:/data/db

volumes:
  mongo_data_ci:

